func_va: 0x141bfe0
func_rva: 0x141bfe0
func_size: 0x33d
func_sig: 55 48 89 E5 41 57 41 56 41 55 41 54 49 89 FC 53 48 8D 1D ?? ?? ?? ?? 48 83 EC 38 48 8D 05 ?? ?? ?? ?? 4C 8B 28 49 8B 45 00 4C 8B B8 60 02 00 00 E8 ?? ?? ?? ??
