func_va: 24293184
func_rva: 24293184
func_size: 495
func_sig: 55 31 D2 48 89 E5 41 57 41 56 41 55 41 54 4C 8D 65 90 53 4C 89 E7 48 89
  F3 31 F6 48 83 EC 68 E8 ?? ?? ?? ?? 4C 8B 2D ?? ?? ?? ?? 48 89 DF 49 8B 45 00 4C
  8B B0 80 02 00 00 E8 ?? ?? ?? ??
vtable_name: CGameRules
vfunc_offset: 536
vfunc_index: 67
func_name: CGameRules_ClientSettingsChanged
