modules:
  - name: engine
    path_windows: game/bin/win64/engine2.dll
    path_linux: game/bin/linuxsteamrt64/libengine2.so

    symbols:
      - name: CServerSideClient_IsHearingClient
        alias:
          - IsHearingClient
        catagory: vfunc

  - name: server
    path_windows: game/csgo/bin/win64/server.dll
    path_linux: game/csgo/bin/linuxsteamrt64/libserver.so

    symbols:
      - name: CSource2Server_vtable
        catagory: vtable

      - name: CCSGameRules_vtable
        catagory: vtable

      - name: CBaseModelEntity_SetModel
        alias:
          - CBaseModelEntity::SetModel
        catagory: func

      - name: CBasePlayerController_SetPlayerName
        alias:
          - CBasePlayerController::SetPlayerName
        catagory: func

      - name: CCSGameRules_FindPickerEntity
        alias:
          - CCSGameRules::FindPickerEntity
        catagory: vfunc
        prerequsite: CCSGameRules_vtable

      - name: CCSGameRules_TerminateRound
        alias:
          - CCSGameRules::TerminateRound
        catagory: func

      - name: CCSPlayer_ItemServices_CanAcquire
        alias:
          - CCSPlayer_ItemServices::CanAcquire
        catagory: func

      - name: CCSPlayer_ItemServices_GiveNamedItem
        alias:
          - CCSPlayer_ItemServices::GiveNamedItem
        catagory: vfunc

      - name: CCSPlayer_WeaponServices_CanUse
        alias:
          - CCSPlayer_WeaponServices::CanUse
        catagory: vfunc

      - name: CCSPlayerController_ChangeTeam
        alias:
          - CCSPlayerController::ChangeTeam
        catagory: vfunc

      - name: CCSPlayerController_InventoryUpdateThink
        alias: 
          - InventoryUpdateThink
          - CCSPlayerController::InventoryUpdateThink
        catagory: func

      - name: CCSPlayerController_Respawn
        alias:
          - CCSPlayerController::Respawn
        catagory: vfunc

      - name: CCSPlayerController_SwitchTeam
        alias:
          - CCSPlayerController::SwitchTeam
        catagory: func

      - name: CCSPlayerPawnBase_PostThink
        alias:
          - CCSPlayerPawnBase::PostThink
        catagory: vfunc

      - name: CSource2Server_Init
        alias:
          - CSource2Server::Init
        catagory: vfunc

      - name: CGameEventManager_Init
        alias:
          - CGameEventManager::Init
        catagory: func

      - name: ClientPrint
        catagory: func

      - name: GetCSWeaponDataFromKey
        catagory: func

      - name: GiveNamedItem
        catagory: func

      - name: UTIL_ClientPrintAll
        catagory: func

      - name: UTIL_Remove
        catagory: func
