modules:
  - name: engine
    path_windows: game/bin/win64/engine2.dll
    path_linux: game/bin/linuxsteamrt64/libengine2.so

    symbols:
      - name: CServerSideClient_IsHearingClient
        alias:
          - IsHearingClient
        catagory: vfunc

  - name: server
    path_windows: game/csgo/bin/win64/server.dll
    path_linux: game/csgo/bin/linuxsteamrt64/libserver.so

    symbols:
      - name: CBaseModelEntity_SetModel
        catagory: func

      - name: CBasePlayerController_SetPlayerName
        catagory: func

      - name: CCSGameRules_FindPickerEntity
        catagory: vfunc

      - name: CCSGameRules_TerminateRound
        catagory: func

      - name: CCSPlayer_ItemServices_CanAcquire
        catagory: func

      - name: CCSPlayer_ItemServices_GiveNamedItem
        catagory: vfunc

      - name: CCSPlayer_WeaponServices_CanUse
        catagory: vfunc

      - name: CCSPlayerController_ChangeTeam
        catagory: vfunc

      - name: CCSPlayerController_InventoryUpdateThink
        alias: 
          - InventoryUpdateThink
        catagory: func

      - name: CCSPlayerController_Respawn
        catagory: vfunc

      - name: CCSPlayerController_SwitchTeam
        catagory: func

      - name: CCSPlayerPawnBase_PostThink
        catagory: vfunc

      - name: CGameEventManager_Init
        catagory: func

      - name: ClientPrint
        catagory: func

      - name: GetCSWeaponDataFromKey
        catagory: func

      - name: GiveNamedItem
        catagory: func

      - name: UTIL_ClientPrintAll
        catagory: func

      - name: UTIL_Remove
        catagory: func
