func_va: '0x1724700'
func_rva: '0x1724700'
func_size: '0x1ef'
func_sig: 55 31 D2 48 89 E5 41 57 41 56 41 55 41 54 4C 8D 65 ??
vtable_name: CGameRules
vfunc_offset: '0x218'
vfunc_index: 67
func_name: CGameRules_ClientSettingsChanged
